name: Docker

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag mssoftware/workspace
      - name: Log into registry
        run: echo {{ github.DOCKER_PASSWORD }} | docker login -u {{ github.DOCKER_USERNAME }} --password-stdin
      - name: Push image
        run: docker push mssoftware/workspace
